# list out the driver program source 
TEST_SRC = example.c

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
#RUN = 1

DEPS = ./Makefile
SUPPORT_OBJS := $(SRC:.c=.o)
include $(CS49N_2021_PATH)/libpi/mk/Makefile.template
